# Generated by Django 3.0.5 on 2024-02-01 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evacuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evacuation_site', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('flood', models.CharField(max_length=255)),
                ('landslides', models.CharField(max_length=255)),
                ('storm_surge', models.CharField(max_length=255)),
                ('earthquake', models.CharField(max_length=255)),
                ('tsunami', models.CharField(max_length=255)),
                ('massive_fire', models.CharField(max_length=255)),
                ('inland_flooding', models.CharField(max_length=255)),
                ('volcanic_phenomena', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
